---

- name: common | Combine dictionary options
  set_fact:
      concourse_web_options_combined: "{{ concourse_web_options_default | combine(concourse_web_options) }}"
      concourse_worker_options_combined: "{{ concourse_worker_options_default | combine(concourse_worker_options) }}"

- name: common | Ensure Concourse group exists
  group:
    name="{{ concourse_group }}"
    state=present

- name: common | Ensure Concourse user exists
  user:
    home="{{ concourse_base_dir }}"
    name="{{ concourse_user }}"
    group="{{ concourse_group }}"
    system="yes"

- name: common | Ensure Concourse directory exists
  file:
    path="{{ item }}"
    state="directory"
    owner="{{ concourse_user }}"
    group="{{ concourse_group }}"
    mode="0750"
  with_items:
    - "{{ concourse_bin_dir }}"
    - "{{ concourse_log_dir }}"

- name: common | Ensure Concourse .ssh dir
  file:
    path="{{ concourse_ssh_dir }}"
    state=directory
    mode=0750
    owner="{{ concourse_user }}"
    group="{{ concourse_group }}"
